### ISSUE TITLE
[Feat] Suggestions for improvement in the project

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [KukretiShubham/surakSA#2]
Thanks for sharing the project. It is awesome. These are few suggestions from my side.
1. Remove unwanted categories which are not in use.
<img src="https://i.imgur.com/PhIZGEk.png">
2. Add essential documents to make the project more inclusive
<img src="https://i.imgur.com/d2xgKms.png">

**Comment by KukretiShubham** [comment]
Thank you for contribution.
